export const SET_CURRENT_STEP = 'SET_CURRENT_STEP'
export const SET_GAME_START = 'SET_GAME_START'
export const SET_CURRENT_STEP_AT = 'SET_CURRENT_STEP_AT'
export const SET_RESTORED_GAME = 'SET_RESTORED_GAME'
